# Generated by Django 5.1.3 on 2024-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=250)),
                ("job", models.CharField(max_length=250)),
                ("salary", models.IntegerField(null=True)),
            ],
        ),
    ]
